export const ApiData = [
    { "id": 1, "title": "Django", "description": "A high-level Python web framework for rapid development." },
    { "id": 2, "title": "React", "description": "A JavaScript library for building user interfaces." },
    { "id": 3, "title": "Next.js", "description": "A React framework for server-rendered applications." },
    { "id": 4, "title": "Vue.js", "description": "A progressive JavaScript framework for building UIs." },
    { "id": 5, "title": "Angular", "description": "A TypeScript-based web application framework by Google." },
    { "id": 6, "title": "Flask", "description": "A lightweight Python framework for building web apps." },
    { "id": 7, "title": "Express.js", "description": "A minimal and flexible Node.js web application framework." },
    { "id": 8, "title": "Ruby on Rails", "description": "A web application framework written in Ruby." },
    { "id": 9, "title": "Laravel", "description": "A PHP framework for web artisans with elegant syntax." },
    { "id": 10, "title": "Spring Boot", "description": "A Java-based framework for microservices and web applications." },
    { "id": 11, "title": "ASP.NET Core", "description": "A cross-platform framework for building modern web apps by Microsoft." },
    { "id": 12, "title": "Svelte", "description": "A framework for building fast, reactive web applications." },
    { "id": 13, "title": "Ember.js", "description": "A framework for creating ambitious web applications." },
    { "id": 14, "title": "Symfony", "description": "A PHP framework for building web applications and APIs." },
    { "id": 15, "title": "CodeIgniter", "description": "A lightweight PHP framework for quick web development." },
    { "id": 16, "title": "CakePHP", "description": "A PHP framework with a flexible architecture for building web apps." },
    { "id": 17, "title": "Meteor.js", "description": "A JavaScript platform for building full-stack web apps." },
    { "id": 18, "title": "Gatsby", "description": "A React-based framework for building static websites." },
    { "id": 19, "title": "Hugo", "description": "A fast and flexible static site generator written in Go." },
    { "id": 20, "title": "Jekyll", "description": "A static site generator perfect for blogs and simple sites." },
    { "id": 21, "title": "Bootstrap", "description": "A popular front-end framework for responsive web design." },
    { "id": 22, "title": "Tailwind CSS", "description": "A utility-first CSS framework for rapidly building custom designs." },
    { "id": 23, "title": "Material-UI", "description": "A React component library based on Google’s Material Design." },
    { "id": 24, "title": "Bulma", "description": "A modern CSS framework based on Flexbox." },
    { "id": 25, "title": "Foundation", "description": "A responsive front-end framework for modern web design." },
    { "id": 26, "title": "Nuxt.js", "description": "A Vue.js framework for building server-rendered applications." },
    { "id": 27, "title": "Alpine.js", "description": "A lightweight JavaScript framework for simple interactions." },
    { "id": 28, "title": "jQuery", "description": "A fast, small, and feature-rich JavaScript library." },
    { "id": 29, "title": "Backbone.js", "description": "A lightweight JavaScript library for structured web apps." },
    { "id": 30, "title": "Knockout.js", "description": "A JavaScript library for creating dynamic user interfaces." }
]
